const KEY='florMoradoDB_v1';
const db=JSON.parse(localStorage.getItem(KEY)||'{"clients":[],"products":[],"sales":[],"seq":1}');
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n||0));
const save=()=>{localStorage.setItem(KEY,JSON.stringify(db)); renderAll();};
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function show(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo({top:0,behavior:'smooth'});} 
$$('.tabs button').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));

function renderClients(){
 $('#saleClient').innerHTML='<option value="">Seleccionar cliente</option>'+db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
 $('#clientList').innerHTML=db.clients.length?db.clients.map(c=>`<div class="row"><div><strong>${esc(c.name)}</strong><div class="meta">${esc(c.phone||'Sin teléfono')} · ${esc(c.address||'Sin dirección')}</div></div><button class="secondary" onclick="deleteClient('${c.id}')">Eliminar</button></div>`).join(''):'<p class="muted">Todavía no hay clientes.</p>';
}
window.deleteClient=x=>{if(confirm('¿Eliminar este cliente?')){db.clients=db.clients.filter(c=>c.id!==x);save();}};
$('#addClient').onclick=()=>{const name=$('#clientName').value.trim();if(!name)return alert('Escribe el nombre del cliente.');db.clients.push({id:id(),name,phone:$('#clientPhone').value.trim(),address:$('#clientAddress').value.trim(),notes:$('#clientNotes').value.trim()});['clientName','clientPhone','clientAddress','clientNotes'].forEach(x=>$('#'+x).value='');save();};

function renderProducts(){
 $('#productList').innerHTML=db.products.length?db.products.map(p=>`<div class="row"><div><strong>${esc(p.name)}</strong><div class="meta">${esc(p.ref||'Sin ref.')} · ${esc(p.category||'Sin categoría')} · Stock: ${p.stock}</div></div><div class="right"><strong>${money(p.price)}</strong><div class="meta">Costo ${money(p.cost)}</div><button class="secondary" onclick="adjustStock('${p.id}')">Ajustar</button></div></div>`).join(''):'<p class="muted">Todavía no hay productos.</p>';
 refreshSaleItemSelects();
}
window.adjustStock=x=>{const p=db.products.find(z=>z.id===x);const n=prompt(`Nuevo stock para ${p.name}:`,p.stock);if(n!==null&&!isNaN(n)){p.stock=Number(n);save();}};
$('#addProduct').onclick=()=>{const name=$('#prodName').value.trim();if(!name)return alert('Escribe el nombre del producto.');db.products.push({id:id(),name,ref:$('#prodRef').value.trim(),category:$('#prodCategory').value.trim(),cost:Number($('#prodCost').value||0),price:Number($('#prodPrice').value||0),stock:Number($('#prodStock').value||0)});['prodName','prodRef','prodCategory','prodCost','prodPrice','prodStock'].forEach(x=>$('#'+x).value='');save();};

function addSaleItem(){const d=document.createElement('div');d.className='sale-item';d.innerHTML=`<label>Producto<select class="item-prod"></select></label><label>Cant.<input class="item-qty" type="number" min="1" value="1"></label><label>Precio<input class="item-price" type="number" min="0" step="1000"></label><button class="remove">×</button>`;$('#saleItems').appendChild(d);d.querySelector('.remove').onclick=()=>{d.remove();calcSale();};d.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',calcSale));d.querySelector('.item-prod').addEventListener('change',e=>{const p=db.products.find(x=>x.id===e.target.value);if(p)d.querySelector('.item-price').value=p.price;calcSale();});refreshSaleItemSelects();}
$('#addSaleItem').onclick=addSaleItem;
function refreshSaleItemSelects(){ $$('.item-prod').forEach(s=>{const cur=s.value;s.innerHTML='<option value="">Seleccionar</option>'+db.products.map(p=>`<option value="${p.id}">${esc(p.name)} (stock ${p.stock})</option>`).join('');s.value=cur;});}
function getSaleDraft(){const items=$$('.sale-item').map(r=>({productId:r.querySelector('.item-prod').value,qty:Number(r.querySelector('.item-qty').value||0),price:Number(r.querySelector('.item-price').value||0)})).filter(x=>x.productId&&x.qty>0);const subtotal=items.reduce((a,x)=>a+x.qty*x.price,0);const shipping=Number($('#saleShipping').value||0),discount=Number($('#saleDiscount').value||0),deposit=Number($('#saleDeposit').value||0);const total=Math.max(0,subtotal+shipping-discount),balance=Math.max(0,total-deposit);return{items,subtotal,shipping,discount,deposit,total,balance};}
function calcSale(){const s=getSaleDraft();$('#saleSubtotal').textContent=money(s.subtotal);$('#saleTotal').textContent=money(s.total);$('#saleBalance').textContent=money(s.balance);}['saleShipping','saleDiscount','saleDeposit'].forEach(x=>$('#'+x).addEventListener('input',calcSale));

$('#saveSale').onclick=()=>{const client=db.clients.find(c=>c.id===$('#saleClient').value);if(!client)return alert('Selecciona un cliente.');const d=getSaleDraft();if(!d.items.length)return alert('Agrega al menos un producto.');for(const it of d.items){const p=db.products.find(x=>x.id===it.productId);if(p.stock<it.qty&&!confirm(`${p.name} tiene stock ${p.stock} y estás vendiendo ${it.qty}. ¿Continuar?`))return;}const number='FM-'+String(db.seq).padStart(4,'0');const sale={id:id(),number,date:$('#saleDate').value||new Date().toISOString().slice(0,10),clientId:client.id,payment:$('#salePayment').value,notes:$('#saleNotes').value.trim(),...d,payments:d.deposit?[{id:id(),date:new Date().toISOString().slice(0,10),amount:d.deposit}]:[]};db.seq++;db.sales.push(sale);for(const it of d.items){const p=db.products.find(x=>x.id===it.productId);p.stock-=it.qty;}save();renderReceipt(sale);resetSale();};
function resetSale(){$('#saleClient').value='';$('#saleShipping').value=0;$('#saleDiscount').value=0;$('#saleDeposit').value=0;$('#saleNotes').value='';$('#saleItems').innerHTML='';addSaleItem();calcSale();}

function renderReceivables(){$('#receivableList').innerHTML=db.sales.filter(s=>s.balance>0).length?db.sales.filter(s=>s.balance>0).map(s=>{const c=db.clients.find(x=>x.id===s.clientId);return `<div class="row"><div><strong>${esc(c?.name||'Cliente')}</strong><div class="meta">${s.number} · ${s.date}</div></div><div class="right"><strong>${money(s.balance)}</strong><div><button onclick="addPayment('${s.id}')">Registrar abono</button></div></div></div>`}).join(''):'<p class="muted">No hay saldos pendientes.</p>';}
window.addPayment=x=>{const s=db.sales.find(z=>z.id===x);const a=Number(prompt(`Saldo actual ${money(s.balance)}. Valor del abono:`)||0);if(a<=0)return;s.payments=s.payments||[];s.payments.push({id:id(),date:new Date().toISOString().slice(0,10),amount:a});s.deposit=(s.deposit||0)+a;s.balance=Math.max(0,s.total-s.deposit);save();};

function renderHistory(){const q=$('#historySearch').value.toLowerCase();const arr=[...db.sales].reverse().filter(s=>{const c=db.clients.find(x=>x.id===s.clientId);return !q||s.number.toLowerCase().includes(q)||(c?.name||'').toLowerCase().includes(q)});$('#historyList').innerHTML=arr.length?arr.map(s=>{const c=db.clients.find(x=>x.id===s.clientId);return `<div class="row"><div><strong>${s.number} · ${esc(c?.name||'Cliente')}</strong><div class="meta">${s.date} · ${money(s.total)}</div></div><div class="right"><span class="badge ${s.balance>0?'debt':'paid'}">${s.balance>0?'Debe '+money(s.balance):'Pagado'}</span><div style="margin-top:8px"><button class="secondary" onclick="openSale('${s.id}')">Ver</button></div></div></div>`}).join(''):'<p class="muted">No hay ventas.</p>';}
$('#historySearch').addEventListener('input',renderHistory);window.openSale=x=>renderReceipt(db.sales.find(s=>s.id===x));

function renderReceipt(s){const c=db.clients.find(x=>x.id===s.clientId);const rows=s.items.map(it=>{const p=db.products.find(x=>x.id===it.productId);return `<tr><td>${esc(p?.name||'Producto')}</td><td>${it.qty}</td><td>${money(it.price)}</td><td>${money(it.qty*it.price)}</td></tr>`}).join('');$('#receipt').innerHTML=`<div class="receipt"><div class="receipt-head"><h2>Flor Morado Muebles</h2><div>Comprobante de venta / Cuenta de cobro</div><strong>${s.number}</strong></div><p><strong>Fecha:</strong> ${s.date}<br><strong>Cliente:</strong> ${esc(c?.name||'')}<br><strong>Teléfono:</strong> ${esc(c?.phone||'')}<br><strong>Dirección:</strong> ${esc(c?.address||'')}</p><table class="receipt-table"><thead><tr><th>Producto</th><th>Cant.</th><th>Precio</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table><div class="receipt-total"><div><span>Subtotal</span><strong>${money(s.subtotal)}</strong></div><div><span>Transporte</span><strong>${money(s.shipping)}</strong></div><div><span>Descuento</span><strong>-${money(s.discount)}</strong></div><div><span>Total</span><strong>${money(s.total)}</strong></div><div><span>Abonado</span><strong>${money(s.deposit)}</strong></div><div><span>Saldo</span><strong>${money(s.balance)}</strong></div></div><p><strong>Forma de pago:</strong> ${esc(s.payment)}</p>${s.notes?`<p><strong>Observaciones:</strong> ${esc(s.notes)}</p>`:''}<p class="muted">Documento interno de venta. No constituye factura electrónica.</p></div>`;$('#modal').classList.remove('hidden');}
$('#closeModal').onclick=$('#closeModal2').onclick=()=>$('#modal').classList.add('hidden');$('#printReceipt').onclick=()=>window.print();

function renderStats(){const now=new Date(),ym=now.toISOString().slice(0,7);const ms=db.sales.filter(s=>s.date.startsWith(ym));$('#statSales').textContent=money(ms.reduce((a,s)=>a+s.total,0));let prof=0;for(const s of ms)for(const it of s.items){const p=db.products.find(x=>x.id===it.productId);prof+=(it.price-(p?.cost||0))*it.qty;}$('#statProfit').textContent=money(prof);$('#statDebt').textContent=money(db.sales.reduce((a,s)=>a+s.balance,0));$('#statLow').textContent=db.products.filter(p=>p.stock<=1).length;}
function renderAll(){renderClients();renderProducts();renderReceivables();renderHistory();renderStats();}

$('#backupBtn').onclick=()=>{const choice=confirm('Aceptar = exportar backup.\nCancelar = importar backup.');if(choice){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='flor-morado-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);}else $('#importFile').click();};
$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.clients||!x.products||!x.sales)throw 0;Object.assign(db,x);save();alert('Backup importado correctamente.');}catch{alert('Archivo de backup no válido.');}};r.readAsText(f);};

$('#saleDate').value=new Date().toISOString().slice(0,10);renderAll();addSaleItem();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
