const KEY='florMoradoDB_v1';
const DEFAULTS={clients:[],products:[],sales:[],cashMovements:[],finance:{accounts:[],transactions:[],recurring:[]},seq:1,settings:{name:'Flor Morado Muebles',phone:'',address:'',email:'',social:'',city:'',footer:'Gracias por su compra.'}};
let stored={};try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
const db={...DEFAULTS,...stored,settings:{...DEFAULTS.settings,...(stored.settings||{})}};
db.clients=Array.isArray(db.clients)?db.clients:[];
db.products=Array.isArray(db.products)?db.products:[];
db.sales=Array.isArray(db.sales)?db.sales:[];
db.cashMovements=Array.isArray(db.cashMovements)?db.cashMovements:[];
db.finance=db.finance&&typeof db.finance==='object'?db.finance:{accounts:[],transactions:[],recurring:[]};
db.finance.accounts=Array.isArray(db.finance.accounts)?db.finance.accounts:[];
db.finance.transactions=Array.isArray(db.finance.transactions)?db.finance.transactions:[];
db.finance.recurring=Array.isArray(db.finance.recurring)?db.finance.recurring:[];
for(const p of db.products){if(p.minStock===undefined)p.minStock=1;}
for(const s of db.sales){
  if(!s.orderStatus)s.orderStatus='Pendiente';
  if(s.deliveryDate===undefined)s.deliveryDate='';
  if(s.actualDeliveryDate===undefined)s.actualDeliveryDate='';
  if(s.shippingExpense===undefined)s.shippingExpense=0;
  if(s.otherExpenses===undefined)s.otherExpenses=0;
  if(!Array.isArray(s.payments))s.payments=[];
  if(!Array.isArray(s.items))s.items=[];
  for(const it of s.items)if(it.customDetails===undefined)it.customDetails='';
  if(s.payments.length){s.deposit=s.payments.reduce((a,p)=>a+Number(p.amount||0),0);s.balance=Math.max(0,Number(s.total||0)-s.deposit);}
}

const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n||0));
const save=()=>{localStorage.setItem(KEY,JSON.stringify(db));renderAll();};
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const activeSales=()=>db.sales.filter(s=>s.orderStatus!=='Cancelada');
let currentReceiptSaleId=null;

function show(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo({top:0,behavior:'smooth'});} 
$$('.tabs button').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));

function clientSales(clientId){return db.sales.filter(s=>s.clientId===clientId&&s.orderStatus!=='Cancelada');}
function renderClients(){
 $('#saleClient').innerHTML='<option value="">Seleccionar cliente</option>'+db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
 $('#clientList').innerHTML=db.clients.length?db.clients.map(c=>{const sales=clientSales(c.id);const total=sales.reduce((a,s)=>a+Number(s.total||0),0);const debt=sales.reduce((a,s)=>a+Number(s.balance||0),0);return `<div class="row"><div><strong>${esc(c.name)}</strong><div class="meta">${esc(c.phone||'Sin teléfono')} · ${esc(c.address||'Sin dirección')}<br>${sales.length} compra(s) · Saldo ${money(debt)}</div></div><div class="right"><div class="row-actions"><button onclick="openClientProfile('${c.id}')">Ver ficha</button><button class="secondary" onclick="editClient('${c.id}')">Editar</button><button class="danger-btn" onclick="deleteClient('${c.id}')">Eliminar</button></div><div class="meta">Compras ${money(total)}</div></div></div>`}).join(''):'<p class="muted">Todavía no hay clientes.</p>';
}
window.deleteClient=x=>{if(db.sales.some(s=>s.clientId===x))return alert('Este cliente tiene ventas registradas. Para conservar el historial no se puede eliminar. Puedes editar sus datos.');if(confirm('¿Eliminar este cliente?')){db.clients=db.clients.filter(c=>c.id!==x);save();}};
window.editClient=x=>{const c=db.clients.find(z=>z.id===x);if(!c)return;$('#clientEditId').value=c.id;$('#clientName').value=c.name||'';$('#clientPhone').value=c.phone||'';$('#clientAddress').value=c.address||'';$('#clientNotes').value=c.notes||'';$('#clientFormTitle').textContent='Editar cliente';$('#addClient').textContent='Guardar cambios';$('#cancelClientEdit').classList.remove('hidden');show('clients');};
function clearClientForm(){['clientEditId','clientName','clientPhone','clientAddress','clientNotes'].forEach(x=>$('#'+x).value='');$('#clientFormTitle').textContent='Clientes';$('#addClient').textContent='Guardar cliente';$('#cancelClientEdit').classList.add('hidden');}
$('#cancelClientEdit').onclick=clearClientForm;
$('#addClient').onclick=()=>{const name=$('#clientName').value.trim();if(!name)return alert('Escribe el nombre del cliente.');const data={name,phone:$('#clientPhone').value.trim(),address:$('#clientAddress').value.trim(),notes:$('#clientNotes').value.trim()};const editId=$('#clientEditId').value;if(editId){const c=db.clients.find(x=>x.id===editId);if(c)Object.assign(c,data);}else db.clients.push({id:id(),...data});clearClientForm();save();};
window.openClientProfile=x=>{const c=db.clients.find(z=>z.id===x);if(!c)return;const sales=[...clientSales(x)].reverse();const total=sales.reduce((a,s)=>a+Number(s.total||0),0);const paid=sales.reduce((a,s)=>a+Number(s.deposit||0),0);const debt=sales.reduce((a,s)=>a+Number(s.balance||0),0);$('#clientProfile').innerHTML=`<div class="profile-head"><h2>${esc(c.name)}</h2><span>${esc(c.phone||'Sin teléfono')}</span></div><div class="profile-grid"><div><span>Total comprado</span><strong>${money(total)}</strong></div><div><span>Total abonado</span><strong>${money(paid)}</strong></div><div><span>Saldo pendiente</span><strong>${money(debt)}</strong></div><div><span>Número de compras</span><strong>${sales.length}</strong></div></div>${c.address?`<p><strong>Dirección:</strong> ${esc(c.address)}</p>`:''}${c.notes?`<p><strong>Notas:</strong> ${esc(c.notes)}</p>`:''}<h3>Historial</h3>${sales.length?sales.map(s=>`<div class="profile-sale" onclick="closeClientAndOpenSale('${s.id}')"><span><strong>${esc(s.number)}</strong><br>${esc(s.date)} · ${esc(s.orderStatus)}</span><strong>${money(s.total)}</strong></div>`).join(''):'<p class="muted">Sin compras.</p>'}`;$('#clientModal').classList.remove('hidden');};
window.closeClientAndOpenSale=x=>{$('#clientModal').classList.add('hidden');renderReceipt(db.sales.find(s=>s.id===x));};
$('#closeClientModal').onclick=()=>$('#clientModal').classList.add('hidden');

function productExtra(p){return [p.measures,p.color,p.material].filter(Boolean).join(' · ')}
function renderProducts(){
 $('#productList').innerHTML=db.products.length?db.products.map(p=>{const low=Number(p.stock||0)<=Number(p.minStock??1);return `<div class="row ${low?'low-stock-row':''}"><div><strong>${esc(p.name)}</strong>${low?'<span class="badge stock">Stock bajo</span>':''}<div class="meta">${esc(p.ref||'Sin ref.')} · ${esc(p.category||'Sin categoría')} · Stock: ${Number(p.stock||0)} / mínimo ${Number(p.minStock??1)}${productExtra(p)?'<br>'+esc(productExtra(p)):''}${p.details?'<br>'+esc(p.details):''}</div></div><div class="right"><strong>${money(p.price)}</strong><div class="meta">Costo ${money(p.cost)}</div><div class="row-actions"><button class="secondary" onclick="editProduct('${p.id}')">Editar</button><button class="secondary" onclick="adjustStock('${p.id}')">Stock</button></div></div></div>`}).join(''):'<p class="muted">Todavía no hay productos.</p>';
 refreshSaleItemSelects();
}
window.adjustStock=x=>{const p=db.products.find(z=>z.id===x);const n=prompt(`Nuevo stock para ${p.name}:`,p.stock);if(n!==null&&!isNaN(n)){p.stock=Number(n);save();}};
window.editProduct=x=>{const p=db.products.find(z=>z.id===x);if(!p)return;$('#prodEditId').value=p.id;$('#prodName').value=p.name||'';$('#prodRef').value=p.ref||'';$('#prodCategory').value=p.category||'';$('#prodMeasures').value=p.measures||'';$('#prodColor').value=p.color||'';$('#prodMaterial').value=p.material||'';$('#prodCost').value=p.cost||0;$('#prodPrice').value=p.price||0;$('#prodStock').value=p.stock||0;$('#prodMinStock').value=p.minStock??1;$('#prodDetails').value=p.details||'';$('#productFormTitle').textContent='Editar producto';$('#addProduct').textContent='Guardar cambios';$('#cancelProductEdit').classList.remove('hidden');show('inventory');window.scrollTo({top:0,behavior:'smooth'});};
function clearProductForm(){['prodEditId','prodName','prodRef','prodCategory','prodMeasures','prodColor','prodMaterial','prodCost','prodPrice','prodStock','prodDetails'].forEach(x=>$('#'+x).value='');$('#prodMinStock').value=1;$('#productFormTitle').textContent='Agregar producto';$('#addProduct').textContent='Guardar producto';$('#cancelProductEdit').classList.add('hidden');}
$('#cancelProductEdit').onclick=clearProductForm;
$('#addProduct').onclick=()=>{const name=$('#prodName').value.trim();if(!name)return alert('Escribe el nombre del producto.');const data={name,ref:$('#prodRef').value.trim(),category:$('#prodCategory').value.trim(),measures:$('#prodMeasures').value.trim(),color:$('#prodColor').value.trim(),material:$('#prodMaterial').value.trim(),cost:Number($('#prodCost').value||0),price:Number($('#prodPrice').value||0),stock:Number($('#prodStock').value||0),minStock:Number($('#prodMinStock').value||0),details:$('#prodDetails').value.trim()};const editId=$('#prodEditId').value;if(editId){const p=db.products.find(x=>x.id===editId);if(p)Object.assign(p,data);}else db.products.push({id:id(),...data});clearProductForm();save();};

function addSaleItem(){const d=document.createElement('div');d.className='sale-item-card';d.innerHTML=`<div class="sale-item"><label>Producto<select class="item-prod"></select></label><label>Cant.<input class="item-qty" type="number" min="1" value="1"></label><label>Precio<input class="item-price" type="number" min="0" step="1000"></label><button class="remove" aria-label="Eliminar producto">×</button></div><label class="custom-label">Personalización / especificaciones de este pedido<textarea class="item-custom" rows="2" placeholder="Ej. Tela gris 014, brazo derecho, 220 × 160 cm, patas color nogal..."></textarea></label>`;$('#saleItems').appendChild(d);d.querySelector('.remove').onclick=()=>{d.remove();calcSale();};d.querySelectorAll('input,select,textarea').forEach(e=>e.addEventListener('input',calcSale));d.querySelector('.item-prod').addEventListener('change',e=>{const p=db.products.find(x=>x.id===e.target.value);if(p)d.querySelector('.item-price').value=p.price;calcSale();});refreshSaleItemSelects();}
$('#addSaleItem').onclick=addSaleItem;
function refreshSaleItemSelects(){ $$('.item-prod').forEach(s=>{const cur=s.value;s.innerHTML='<option value="">Seleccionar</option>'+db.products.map(p=>`<option value="${p.id}">${esc(p.name)} (stock ${Number(p.stock||0)})</option>`).join('');s.value=cur;});}
function getSaleDraft(){const items=$$('.sale-item-card').map(card=>{const r=card.querySelector('.sale-item'),productId=r.querySelector('.item-prod').value,p=db.products.find(x=>x.id===productId);return{productId,qty:Number(r.querySelector('.item-qty').value||0),price:Number(r.querySelector('.item-price').value||0),customDetails:card.querySelector('.item-custom').value.trim(),name:p?.name||'',ref:p?.ref||'',measures:p?.measures||'',color:p?.color||'',material:p?.material||'',details:p?.details||'',cost:Number(p?.cost||0)}}).filter(x=>x.productId&&x.qty>0);const subtotal=items.reduce((a,x)=>a+x.qty*x.price,0);const shipping=Number($('#saleShipping').value||0),discount=Number($('#saleDiscount').value||0),deposit=Number($('#saleDeposit').value||0),shippingExpense=Number($('#saleShippingExpense').value||0),otherExpenses=Number($('#saleOtherExpenses').value||0);const total=Math.max(0,subtotal+shipping-discount),balance=Math.max(0,total-deposit),cogs=items.reduce((a,x)=>a+Number(x.cost||0)*x.qty,0),profit=total-cogs-shippingExpense-otherExpenses;return{items,subtotal,shipping,discount,deposit,total,balance,shippingExpense,otherExpenses,profit};}
function calcSale(){const s=getSaleDraft();$('#saleSubtotal').textContent=money(s.subtotal);$('#saleTotal').textContent=money(s.total);$('#saleBalance').textContent=money(s.balance);$('#saleProfit').textContent=money(s.profit);}['saleShipping','saleDiscount','saleDeposit','saleShippingExpense','saleOtherExpenses'].forEach(x=>$('#'+x).addEventListener('input',calcSale));

$('#saveSale').onclick=()=>{const client=db.clients.find(c=>c.id===$('#saleClient').value);if(!client)return alert('Selecciona un cliente.');const d=getSaleDraft();if(!d.items.length)return alert('Agrega al menos un producto.');for(const it of d.items){const p=db.products.find(x=>x.id===it.productId);if(p&&Number(p.stock)<it.qty&&!confirm(`${p.name} tiene stock ${p.stock} y estás vendiendo ${it.qty}. ¿Continuar?`))return;}const number='FM-'+String(db.seq).padStart(4,'0');const sale={id:id(),number,date:$('#saleDate').value||today(),deliveryDate:$('#saleDeliveryDate').value||'',actualDeliveryDate:$('#saleOrderStatus').value==='Entregada'?today():'',orderStatus:$('#saleOrderStatus').value||'Pendiente',clientId:client.id,payment:$('#salePayment').value,notes:$('#saleNotes').value.trim(),...d,payments:d.deposit?[{id:id(),date:$('#saleDate').value||today(),amount:d.deposit,method:$('#salePayment').value,note:'Abono inicial'}]:[]};db.seq++;db.sales.push(sale);for(const it of d.items){const p=db.products.find(x=>x.id===it.productId);if(p)p.stock-=it.qty;}save();renderReceipt(sale);resetSale();};
function resetSale(){$('#saleClient').value='';$('#saleDate').value=today();$('#saleDeliveryDate').value='';$('#saleOrderStatus').value='Pendiente';$('#saleShipping').value=0;$('#saleDiscount').value=0;$('#saleDeposit').value=0;$('#saleShippingExpense').value=0;$('#saleOtherExpenses').value=0;$('#saleNotes').value='';$('#saleItems').innerHTML='';addSaleItem();calcSale();}

function registerPayment(saleId){const s=db.sales.find(z=>z.id===saleId);if(!s||s.orderStatus==='Cancelada')return alert('No se pueden registrar abonos en una venta cancelada.');if(s.balance<=0)return;const raw=prompt(`Saldo actual ${money(s.balance)}.\nValor del abono:`);if(raw===null)return;const a=Number(String(raw).replace(/[^0-9.-]/g,''));if(!a||a<=0)return alert('Ingresa un valor válido.');if(a>s.balance&&!confirm(`El abono supera el saldo por ${money(a-s.balance)}. ¿Registrarlo de todas formas?`))return;const date=prompt('Fecha del abono (AAAA-MM-DD):',today())||today();const method=prompt('Método de pago:',s.payment||'Efectivo')||'';const note=prompt('Nota del abono (opcional):','')||'';s.payments=s.payments||[];s.payments.push({id:id(),date,amount:a,method,note});s.deposit=(s.payments||[]).reduce((sum,p)=>sum+Number(p.amount||0),0);s.balance=Math.max(0,s.total-s.deposit);save();if(!$('#modal').classList.contains('hidden'))renderReceipt(s);}
window.addPayment=registerPayment;
function paymentStatus(s){if(Number(s.balance||0)<=0)return 'Pagada';if(Number(s.deposit||0)>0)return 'Abonada';return 'Pendiente';}
function renderReceivables(){const due=activeSales().filter(s=>s.balance>0);$('#receivableList').innerHTML=due.length?due.map(s=>{const c=db.clients.find(x=>x.id===s.clientId);return `<div class="row"><div><strong>${esc(c?.name||'Cliente')}</strong><div class="meta">${s.number} · ${s.date}${s.deliveryDate?` · Entrega ${esc(s.deliveryDate)}`:''} · Total ${money(s.total)}</div></div><div class="right"><strong>${money(s.balance)}</strong><div class="row-actions"><button onclick="addPayment('${s.id}')">Registrar abono</button><button class="secondary" onclick="openSale('${s.id}')">Ver</button></div></div></div>`}).join(''):'<p class="muted">No hay saldos pendientes.</p>';}

const ORDER_STATUSES=['Pendiente','En producción','Listo para entregar','Entregada','Cancelada'];
function setOrderStatus(saleId){const s=db.sales.find(z=>z.id===saleId);if(!s)return;const menu=ORDER_STATUSES.map((x,i)=>`${i+1}. ${x}`).join('\n');const raw=prompt(`Estado actual: ${s.orderStatus||'Pendiente'}\n\n${menu}\n\nEscribe el número del nuevo estado:`);if(raw===null)return;const next=ORDER_STATUSES[Number(raw)-1];if(!next)return alert('Opción no válida.');if(next==='Cancelada'&&s.orderStatus!=='Cancelada'){if(!confirm('Al cancelar la venta, dejará de contar en ventas/cartera y las unidades se devolverán al inventario. Los abonos ya recibidos se conservarán en el historial de caja. ¿Continuar?'))return;for(const it of s.items||[]){const p=db.products.find(x=>x.id===it.productId);if(p)p.stock=Number(p.stock||0)+Number(it.qty||0);}s.stockRestoredOnCancel=true;}
 if(s.orderStatus==='Cancelada'&&next!=='Cancelada'&&s.stockRestoredOnCancel){for(const it of s.items||[]){const p=db.products.find(x=>x.id===it.productId);if(p)p.stock=Number(p.stock||0)-Number(it.qty||0);}s.stockRestoredOnCancel=false;}
 s.orderStatus=next;if(next==='Entregada'&&!s.actualDeliveryDate)s.actualDeliveryDate=today();if(next!=='Entregada')s.actualDeliveryDate='';save();if(currentReceiptSaleId===saleId)renderReceipt(s);}
window.changeSaleStatus=setOrderStatus;

function renderHistory(){const q=$('#historySearch').value.toLowerCase(),status=$('#historyStatus').value;const arr=[...db.sales].reverse().filter(s=>{const c=db.clients.find(x=>x.id===s.clientId);return (!q||s.number.toLowerCase().includes(q)||(c?.name||'').toLowerCase().includes(q))&&(!status||s.orderStatus===status)});$('#historyList').innerHTML=arr.length?arr.map(s=>{const c=db.clients.find(x=>x.id===s.clientId),ps=paymentStatus(s);return `<div class="row"><div><strong>${s.number} · ${esc(c?.name||'Cliente')}</strong><div class="meta">${s.date}${s.deliveryDate?` · Entrega ${esc(s.deliveryDate)}`:''} · ${money(s.total)}</div><div class="badge-row"><span class="badge order ${statusClass(s.orderStatus)}">${esc(s.orderStatus||'Pendiente')}</span><span class="badge ${ps==='Pagada'?'paid':ps==='Abonada'?'partial':'debt'}">${ps}${s.balance>0?' · '+money(s.balance):''}</span></div></div><div class="right"><div class="meta">Utilidad ${money(saleProfit(s))}</div><div class="row-actions">${s.balance>0&&s.orderStatus!=='Cancelada'?`<button onclick="addPayment('${s.id}')">+ Abono</button>`:''}<button class="secondary" onclick="changeSaleStatus('${s.id}')">Estado</button><button class="secondary" onclick="openSale('${s.id}')">Ver</button><button class="danger-btn" onclick="deleteSale('${s.id}')">Eliminar</button></div></div></div>`}).join(''):'<p class="muted">No hay ventas.</p>';}
function statusClass(s){return s==='Entregada'?'delivered':s==='Cancelada'?'cancelled':s==='Listo para entregar'?'ready':s==='En producción'?'production':'pending';}
function deleteSale(saleId){const s=db.sales.find(z=>z.id===saleId);if(!s)return;const c=db.clients.find(x=>x.id===s.clientId);const ok=confirm(`¿Eliminar definitivamente ${s.number}${c?.name?' de '+c.name:''}?\n\nSe eliminarán también sus abonos y el saldo pendiente. Las unidades vendidas se devolverán al inventario si todavía no fueron devueltas por una cancelación.\n\nEsta acción no se puede deshacer.`);if(!ok)return;if(!s.stockRestoredOnCancel){for(const it of (s.items||[])){const p=db.products.find(x=>x.id===it.productId);if(p)p.stock=Number(p.stock||0)+Number(it.qty||0);}}db.sales=db.sales.filter(z=>z.id!==saleId);if(currentReceiptSaleId===saleId){$('#modal').classList.add('hidden');currentReceiptSaleId=null;}save();}
window.deleteSale=deleteSale;
$('#historySearch').addEventListener('input',renderHistory);$('#historyStatus').addEventListener('change',renderHistory);window.openSale=x=>renderReceipt(db.sales.find(s=>s.id===x));

function receiptContact(){const b=db.settings;return [b.address,[b.city,b.phone].filter(Boolean).join(' · '),b.email,b.social].filter(Boolean).map(esc).join('<br>')}
function itemDescription(it){const p=db.products.find(x=>x.id===it.productId)||{};const d={name:it.name||p.name||'Producto',ref:it.ref||p.ref||'',measures:it.measures||p.measures||'',color:it.color||p.color||'',material:it.material||p.material||'',details:it.details||p.details||'',customDetails:it.customDetails||''};const extra=[d.ref?`Ref. ${d.ref}`:'',d.measures,d.color,d.material,d.details].filter(Boolean).map(esc).join(' · ');return `<strong>${esc(d.name)}</strong>${extra?`<span class="item-detail">${extra}</span>`:''}${d.customDetails?`<span class="item-custom-print"><b>Personalización:</b> ${esc(d.customDetails)}</span>`:''}`;}
function renderReceipt(s){if(!s)return;currentReceiptSaleId=s.id;const c=db.clients.find(x=>x.id===s.clientId);const rows=s.items.map(it=>`<tr><td>${itemDescription(it)}</td><td>${it.qty}</td><td>${money(it.price)}</td><td>${money(it.qty*it.price)}</td></tr>`).join('');const pays=(s.payments||[]);const payRows=pays.length?pays.map((p,i)=>`<div class="payment-row"><span>${i+1}. ${esc(p.date||'')} ${p.method?`· ${esc(p.method)}`:''}${p.note?` · ${esc(p.note)}`:''}</span><strong>${money(p.amount)}</strong></div>`).join(''):'<span class="muted">Sin abonos registrados.</span>';const b=db.settings;$('#receipt').innerHTML=`<div class="receipt"><div class="receipt-head"><img src="logo-flor-morado.jpg" class="receipt-logo" alt="Logo"><div class="receipt-brand"><div class="receipt-kicker">COMPROBANTE DE VENTA / CUENTA DE COBRO</div><h2>${esc(b.name||'Flor Morado Muebles')}</h2><div class="contact">${receiptContact()}</div></div><div class="receipt-number"><span>Comprobante</span><strong>${esc(s.number)}</strong><span>${esc(s.date)}</span></div></div><div class="client-box"><strong>Cliente:</strong> ${esc(c?.name||'')}<br>${c?.phone?`<strong>Teléfono:</strong> ${esc(c.phone)}<br>`:''}${c?.address?`<strong>Dirección:</strong> ${esc(c.address)}<br>`:''}<strong>Estado del pedido:</strong> ${esc(s.orderStatus||'Pendiente')}${s.deliveryDate?`<br><strong>Fecha prometida de entrega:</strong> ${esc(s.deliveryDate)}`:''}${s.actualDeliveryDate?`<br><strong>Entregado:</strong> ${esc(s.actualDeliveryDate)}`:''}</div><table class="receipt-table"><thead><tr><th>Producto / descripción</th><th>Cant.</th><th>Precio</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table><div class="receipt-total"><div><span>Subtotal</span><strong>${money(s.subtotal)}</strong></div><div><span>Transporte</span><strong>${money(s.shipping)}</strong></div><div><span>Descuento</span><strong>-${money(s.discount)}</strong></div><div class="grand"><span>Total</span><strong>${money(s.total)}</strong></div><div><span>Abonado</span><strong>${money(s.deposit)}</strong></div><div class="grand"><span>Saldo</span><strong>${money(s.balance)}</strong></div></div><div class="payments-box"><h4>Abonos registrados</h4>${payRows}</div><p><strong>Forma de pago inicial:</strong> ${esc(s.payment||'')}</p>${s.notes?`<p><strong>Observaciones:</strong> ${esc(s.notes)}</p>`:''}<div class="receipt-footer">${b.footer?`<div>${esc(b.footer)}</div>`:''}<div>Documento interno de venta. No constituye factura electrónica.</div></div></div>`;$('#paymentFromReceipt').classList.toggle('hidden',!(s.balance>0&&s.orderStatus!=='Cancelada'));$('#modal').classList.remove('hidden');}
$('#paymentFromReceipt').onclick=()=>currentReceiptSaleId&&registerPayment(currentReceiptSaleId);$('#statusFromReceipt').onclick=()=>currentReceiptSaleId&&setOrderStatus(currentReceiptSaleId);$('#deleteReceipt').onclick=()=>currentReceiptSaleId&&deleteSale(currentReceiptSaleId);$('#closeModal').onclick=$('#closeModal2').onclick=()=>{$('#modal').classList.add('hidden');currentReceiptSaleId=null;};$('#printReceipt').onclick=()=>window.print();

function saleProfit(s){const cogs=(s.items||[]).reduce((a,it)=>{const p=db.products.find(x=>x.id===it.productId);const cost=('cost'in it)?Number(it.cost||0):Number(p?.cost||0);return a+cost*Number(it.qty||0)},0);return Number(s.total||0)-cogs-Number(s.shippingExpense||0)-Number(s.otherExpenses||0);}
function virtualCashMovements(){const arr=[];for(const s of db.sales){const c=db.clients.find(x=>x.id===s.clientId);for(const p of s.payments||[])arr.push({id:'pay_'+p.id,date:p.date||s.date,type:'income',category:'Abono cliente',note:`${s.number} · ${c?.name||'Cliente'}${p.note?' · '+p.note:''}`,amount:Number(p.amount||0),automatic:true,saleId:s.id});if(s.orderStatus!=='Cancelada'&&Number(s.shippingExpense||0)>0)arr.push({id:'ship_'+s.id,date:s.date,type:'expense',category:'Transporte de venta',note:s.number,amount:Number(s.shippingExpense||0),automatic:true,saleId:s.id});if(s.orderStatus!=='Cancelada'&&Number(s.otherExpenses||0)>0)arr.push({id:'other_'+s.id,date:s.date,type:'expense',category:'Otros gastos de venta',note:s.number,amount:Number(s.otherExpenses||0),automatic:true,saleId:s.id});}return [...arr,...db.cashMovements];}
function renderCash(){const all=virtualCashMovements().sort((a,b)=>String(b.date).localeCompare(String(a.date)));const ym=today().slice(0,7),month=all.filter(m=>String(m.date||'').startsWith(ym));const inc=month.filter(m=>m.type==='income').reduce((a,m)=>a+Number(m.amount||0),0),exp=month.filter(m=>m.type==='expense').reduce((a,m)=>a+Number(m.amount||0),0),balance=all.reduce((a,m)=>a+(m.type==='income'?1:-1)*Number(m.amount||0),0);$('#cashIncomeMonth').textContent=money(inc);$('#cashExpenseMonth').textContent=money(exp);$('#cashBalanceAll').textContent=money(balance);$('#cashList').innerHTML=all.length?all.map(m=>`<div class="row"><div><strong>${esc(m.category||'Movimiento')}</strong><div class="meta">${esc(m.date||'')} · ${esc(m.note||'')}${m.automatic?' · Automático':''}</div></div><div class="right"><strong class="${m.type==='income'?'money-in':'money-out'}">${m.type==='income'?'+':'-'}${money(m.amount)}</strong>${!m.automatic?`<div class="row-actions"><button class="danger-btn" onclick="deleteCashMovement('${m.id}')">Eliminar</button></div>`:''}</div></div>`).join(''):'<p class="muted">Todavía no hay movimientos.</p>';}
$('#addCashMovement').onclick=()=>{const amount=Number($('#cashAmount').value||0);if(amount<=0)return alert('Ingresa un valor válido.');db.cashMovements.push({id:id(),date:$('#cashDate').value||today(),type:$('#cashType').value,category:$('#cashCategory').value.trim()||($('#cashType').value==='expense'?'Gasto':'Ingreso adicional'),amount,note:$('#cashNote').value.trim()});$('#cashAmount').value='';$('#cashCategory').value='';$('#cashNote').value='';save();};
window.deleteCashMovement=x=>{if(confirm('¿Eliminar este movimiento manual?')){db.cashMovements=db.cashMovements.filter(m=>m.id!==x);save();}};

function renderStats(){const ym=today().slice(0,7);const ms=activeSales().filter(s=>String(s.date||'').startsWith(ym));$('#statSales').textContent=money(ms.reduce((a,s)=>a+Number(s.total||0),0));$('#statProfit').textContent=money(ms.reduce((a,s)=>a+saleProfit(s),0));$('#statDebt').textContent=money(activeSales().reduce((a,s)=>a+Number(s.balance||0),0));$('#statLow').textContent=db.products.filter(p=>Number(p.stock||0)<=Number(p.minStock??1)).length;const cash=virtualCashMovements(),cashMonth=cash.filter(m=>String(m.date||'').startsWith(ym));$('#statCollected').textContent=money(cashMonth.filter(m=>m.type==='income'&&m.category==='Abono cliente').reduce((a,m)=>a+Number(m.amount||0),0));$('#statExpenses').textContent=money(cashMonth.filter(m=>m.type==='expense').reduce((a,m)=>a+Number(m.amount||0),0));$('#statCash').textContent=money(cash.reduce((a,m)=>a+(m.type==='income'?1:-1)*Number(m.amount||0),0));$('#statPending').textContent=activeSales().filter(s=>s.orderStatus!=='Entregada').length;renderUpcomingDeliveries();}
function renderUpcomingDeliveries(){const arr=activeSales().filter(s=>s.deliveryDate&&s.orderStatus!=='Entregada').sort((a,b)=>sDate(a.deliveryDate)-sDate(b.deliveryDate)).slice(0,6);$('#upcomingDeliveries').innerHTML=arr.length?arr.map(s=>{const c=db.clients.find(x=>x.id===s.clientId);const late=s.deliveryDate<today();return `<div class="row"><div><strong>${esc(s.number)} · ${esc(c?.name||'Cliente')}</strong><div class="meta">${late?'⚠️ Vencida':'Entrega'} ${esc(s.deliveryDate)} · ${esc(s.orderStatus)}</div></div><button class="secondary" onclick="openSale('${s.id}')">Ver</button></div>`}).join(''):'<p class="muted">No hay entregas programadas.</p>';}
function sDate(x){return new Date(x+'T00:00:00').getTime()||0;}

function renderSettings(){const b=db.settings;$('#bizName').value=b.name||'';$('#bizPhone').value=b.phone||'';$('#bizAddress').value=b.address||'';$('#bizEmail').value=b.email||'';$('#bizSocial').value=b.social||'';$('#bizCity').value=b.city||'';$('#bizFooter').value=b.footer||'';}
$('#saveSettings').onclick=()=>{db.settings={name:$('#bizName').value.trim()||'Flor Morado Muebles',phone:$('#bizPhone').value.trim(),address:$('#bizAddress').value.trim(),email:$('#bizEmail').value.trim(),social:$('#bizSocial').value.trim(),city:$('#bizCity').value.trim(),footer:$('#bizFooter').value.trim()};save();alert('Datos del negocio guardados.');};


// ===== FINANZAS V1.3 =====
const FIN_ASSET_TYPES=['cash','savings','checking','wallet','other'];
const FIN_LIABILITY_TYPES=['credit','debt'];
const FIN_TYPE_LABELS={cash:'Efectivo',savings:'Ahorros',checking:'Cuenta corriente',wallet:'Billetera digital',credit:'Tarjeta de crédito',debt:'Deuda / préstamo',other:'Otra'};
function finIsLiability(a){return a&&FIN_LIABILITY_TYPES.includes(a.type)}
function finAccount(id){return db.finance.accounts.find(a=>a.id===id)}
function finBalance(a){
  let bal=Number(a.opening||0);
  for(const t of db.finance.transactions){
    const n=Number(t.amount||0);
    if(finIsLiability(a)){
      if(t.type==='charge'&&t.toId===a.id)bal+=n;
      if(t.type==='payment'&&t.toId===a.id)bal-=n;
      if(t.type==='transfer'&&t.toId===a.id)bal-=n;
      if(t.type==='transfer'&&t.fromId===a.id)bal+=n;
    }else{
      if(t.type==='income'&&t.toId===a.id)bal+=n;
      if(t.type==='expense'&&t.fromId===a.id)bal-=n;
      if(t.type==='transfer'&&t.fromId===a.id)bal-=n;
      if(t.type==='transfer'&&t.toId===a.id)bal+=n;
      if(t.type==='payment'&&t.fromId===a.id)bal-=n;
    }
  }
  return bal;
}
function finMonthTx(){const ym=today().slice(0,7);return db.finance.transactions.filter(t=>String(t.date||'').startsWith(ym));}
function finIncomeExpense(t){
  if(t.type==='income')return {income:Number(t.amount||0),expense:0};
  if(t.type==='expense')return {income:0,expense:Number(t.amount||0)};
  if(t.type==='charge')return {income:0,expense:Number(t.amount||0)};
  return {income:0,expense:0};
}
function finDaysElapsed(){return Math.max(1,new Date().getDate())}
function finEscAccountOptions(includeLiabilities=true){return db.finance.accounts.filter(a=>includeLiabilities||!finIsLiability(a)).map(a=>`<option value="${a.id}">${esc(a.name)} · ${esc(FIN_TYPE_LABELS[a.type]||a.type)}</option>`).join('')}
function finRenderSelectors(){
 const all='<option value="">Seleccionar cuenta</option>'+finEscAccountOptions(true);
 const assets='<option value="">Seleccionar cuenta</option>'+finEscAccountOptions(false);
 $('#finTxFrom').innerHTML=all; $('#finTxTo').innerHTML=all;
 $('#finRecurringAccount').innerHTML=assets;
 const cur=$('#finMovementFilter').value; $('#finMovementFilter').innerHTML='<option value="">Todas las cuentas</option>'+finEscAccountOptions(true); if([...$('#finMovementFilter').options].some(o=>o.value===cur))$('#finMovementFilter').value=cur;
}
function finRenderAccounts(){
 const wrap=$('#finAccounts'); if(!wrap)return;
 wrap.innerHTML=db.finance.accounts.length?db.finance.accounts.map(a=>{const b=finBalance(a),liab=finIsLiability(a);const limit=Number(a.limit||0),avail=a.type==='credit'&&limit?Math.max(0,limit-b):null;return `<div class="finance-account ${liab?'liability':''}"><div class="account-icon">${a.type==='credit'?'💳':a.type==='debt'?'📉':a.type==='cash'?'💵':a.type==='savings'?'🏦':'💰'}</div><div class="account-main"><strong>${esc(a.name)}</strong><span>${esc(FIN_TYPE_LABELS[a.type]||a.type)}${a.note?' · '+esc(a.note):''}</span>${a.type==='credit'&&limit?`<small>Cupo disponible ${money(avail)} de ${money(limit)}</small>`:''}${(a.cutoff||a.dueDay)?`<small>${a.cutoff?'Corte día '+a.cutoff:''}${a.cutoff&&a.dueDay?' · ':''}${a.dueDay?'Pago día '+a.dueDay:''}</small>`:''}</div><div class="account-balance"><span>${liab?'Saldo adeudado':'Saldo'}</span><strong>${money(Math.max(0,b))}</strong><div class="row-actions"><button class="secondary" onclick="editFinAccount('${a.id}')">Editar</button><button class="danger-btn" onclick="deleteFinAccount('${a.id}')">Eliminar</button></div></div></div>`}).join(''):'<p class="muted">Aún no has creado cuentas. Empieza por Efectivo, Nequi, Ahorros o una tarjeta/deuda.</p>';
}
function renderFinance(){
 if(!$('#finAccounts'))return; finRenderSelectors();finRenderAccounts();
 const assets=db.finance.accounts.filter(a=>!finIsLiability(a)).reduce((s,a)=>s+finBalance(a),0);
 const debts=db.finance.accounts.filter(finIsLiability).reduce((s,a)=>s+Math.max(0,finBalance(a)),0);
 const m=finMonthTx();let inc=0,exp=0;for(const t of m){const x=finIncomeExpense(t);inc+=x.income;exp+=x.expense;}
 $('#finAvailable').textContent=money(assets);$('#finDebt').textContent=money(debts);$('#finNetWorth').textContent=money(assets-debts);$('#finMonthNet').textContent=money(inc-exp);$('#finMonthIncome').textContent=money(inc);$('#finMonthExpense').textContent=money(exp);$('#finDailyExpense').textContent=money(exp/finDaysElapsed());
 const now=new Date(),day=now.getDate();const upcoming=db.finance.recurring.filter(r=>r.active!==false&&Number(r.day||1)>=day).reduce((s,r)=>s+Number(r.amount||0),0);$('#finUpcomingTotal').textContent=money(upcoming);
 $('#finMonthSummary').innerHTML=`<div><span>Ingreso promedio/día</span><strong>${money(inc/finDaysElapsed())}</strong></div><div><span>Gasto promedio/día</span><strong>${money(exp/finDaysElapsed())}</strong></div><div><span>Disponible menos compromisos</span><strong>${money(assets-upcoming)}</strong></div>`;
 const cats={};for(const t of m){const x=finIncomeExpense(t);if(x.expense>0)cats[t.category||'Sin categoría']=(cats[t.category||'Sin categoría']||0)+x.expense;}const max=Math.max(1,...Object.values(cats));$('#finCategorySummary').innerHTML=Object.keys(cats).length?Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`<div class="catbar"><div><span>${esc(k)}</span><strong>${money(v)}</strong></div><i><b style="width:${Math.max(3,Math.round(v/max*100))}%"></b></i></div>`).join(''):'<p class="muted small">Sin gastos registrados este mes.</p>';
 finRenderRecurring();finRenderMovements();
}
function finOpenAccountForm(a=null){$('#finAccountForm').classList.remove('hidden');$('#finAccountEditId').value=a?.id||'';$('#finAccountName').value=a?.name||'';$('#finAccountType').value=a?.type||'cash';$('#finAccountOpening').value=Number(a?.opening||0);$('#finAccountLimit').value=Number(a?.limit||0);$('#finAccountCutoff').value=a?.cutoff||'';$('#finAccountDueDay').value=a?.dueDay||'';$('#finAccountNote').value=a?.note||'';finUpdateOpeningLabel();}
function finCloseAccountForm(){$('#finAccountForm').classList.add('hidden');$('#finAccountEditId').value='';}
function finUpdateOpeningLabel(){const liability=FIN_LIABILITY_TYPES.includes($('#finAccountType').value);$('#finOpeningLabel').childNodes[0].nodeValue=liability?'Deuda / saldo usado inicial':'Saldo inicial';}
$('#toggleAccountForm').onclick=()=>finOpenAccountForm();$('#cancelFinAccount').onclick=finCloseAccountForm;$('#finAccountType').onchange=finUpdateOpeningLabel;
$('#saveFinAccount').onclick=()=>{const name=$('#finAccountName').value.trim();if(!name)return alert('Escribe un nombre para la cuenta.');const data={name,type:$('#finAccountType').value,opening:Number($('#finAccountOpening').value||0),limit:Number($('#finAccountLimit').value||0),cutoff:Number($('#finAccountCutoff').value||0)||'',dueDay:Number($('#finAccountDueDay').value||0)||'',note:$('#finAccountNote').value.trim()};const eid=$('#finAccountEditId').value;if(eid){const a=finAccount(eid);if(a)Object.assign(a,data);}else db.finance.accounts.push({id:id(),...data});finCloseAccountForm();save();};
window.editFinAccount=x=>{const a=finAccount(x);if(a){finOpenAccountForm(a);show('finance');}};
window.deleteFinAccount=x=>{if(db.finance.transactions.some(t=>t.fromId===x||t.toId===x)||db.finance.recurring.some(r=>r.accountId===x))return alert('Esta cuenta tiene movimientos o pagos recurrentes. Elimínalos primero para conservar el historial.');if(confirm('¿Eliminar esta cuenta?')){db.finance.accounts=db.finance.accounts.filter(a=>a.id!==x);save();}};
function finRenderRecurring(){const box=$('#finRecurringList');box.innerHTML=db.finance.recurring.length?db.finance.recurring.sort((a,b)=>Number(a.day)-Number(b.day)).map(r=>{const a=finAccount(r.accountId);return `<div class="row"><div><strong>${esc(r.name)}</strong><div class="meta">${r.type==='income'?'Ingreso':'Gasto'} · ${esc(r.category||'Sin categoría')} · Día ${r.day} · ${esc(a?.name||'Sin cuenta')}</div></div><div class="right"><strong class="${r.type==='income'?'money-in':'money-out'}">${money(r.amount)}</strong><div class="row-actions"><button class="secondary" onclick="postRecurring('${r.id}')">Registrar ahora</button><button class="secondary" onclick="editFinRecurring('${r.id}')">Editar</button><button class="danger-btn" onclick="deleteFinRecurring('${r.id}')">Eliminar</button></div></div></div>`}).join(''):'<p class="muted">No tienes movimientos recurrentes configurados.</p>';}
function finRecurringForm(r=null){$('#finRecurringForm').classList.remove('hidden');$('#finRecurringEditId').value=r?.id||'';$('#finRecurringName').value=r?.name||'';$('#finRecurringType').value=r?.type||'expense';$('#finRecurringCategory').value=r?.category||'';$('#finRecurringAmount').value=Number(r?.amount||0)||'';$('#finRecurringAccount').value=r?.accountId||'';$('#finRecurringDay').value=r?.day||1;}
$('#toggleRecurringForm').onclick=()=>finRecurringForm();$('#cancelFinRecurring').onclick=()=>$('#finRecurringForm').classList.add('hidden');
$('#saveFinRecurring').onclick=()=>{const name=$('#finRecurringName').value.trim(),amount=Number($('#finRecurringAmount').value||0),accountId=$('#finRecurringAccount').value;if(!name||amount<=0||!accountId)return alert('Completa concepto, valor y cuenta.');const d={name,type:$('#finRecurringType').value,category:$('#finRecurringCategory').value.trim()||'Otros',amount,accountId,day:Math.min(31,Math.max(1,Number($('#finRecurringDay').value||1))),active:true};const eid=$('#finRecurringEditId').value;if(eid){const r=db.finance.recurring.find(x=>x.id===eid);if(r)Object.assign(r,d);}else db.finance.recurring.push({id:id(),...d});$('#finRecurringForm').classList.add('hidden');save();};
window.editFinRecurring=x=>{const r=db.finance.recurring.find(z=>z.id===x);if(r)finRecurringForm(r)};window.deleteFinRecurring=x=>{if(confirm('¿Eliminar este recurrente?')){db.finance.recurring=db.finance.recurring.filter(r=>r.id!==x);save();}};
window.postRecurring=x=>{const r=db.finance.recurring.find(z=>z.id===x);if(!r)return;const exists=db.finance.transactions.some(t=>t.recurringId===r.id&&String(t.date||'').slice(0,7)===today().slice(0,7));if(exists&&!confirm('Ya registraste este recurrente este mes. ¿Registrar otro igualmente?'))return;db.finance.transactions.push({id:id(),date:today(),type:r.type,fromId:r.type==='expense'?r.accountId:'',toId:r.type==='income'?r.accountId:'',category:r.category,amount:Number(r.amount),note:r.name,recurringId:r.id});save();};
function finTxLabel(t){const f=finAccount(t.fromId),to=finAccount(t.toId);if(t.type==='income')return `Ingreso · ${esc(to?.name||'')}`;if(t.type==='expense')return `Gasto · ${esc(f?.name||'')}`;if(t.type==='transfer')return `${esc(f?.name||'')} → ${esc(to?.name||'')}`;if(t.type==='charge')return `Cargo · ${esc(to?.name||'')}`;if(t.type==='payment')return `Abono · ${esc(f?.name||'')} → ${esc(to?.name||'')}`;return t.type;}
function finRenderMovements(){const filter=$('#finMovementFilter').value;let arr=[...db.finance.transactions];if(filter)arr=arr.filter(t=>t.fromId===filter||t.toId===filter);arr.sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#finMovements').innerHTML=arr.length?arr.slice(0,150).map(t=>{const sign=t.type==='income'?'+':(t.type==='expense'||t.type==='charge')?'-':'';const cls=t.type==='income'?'money-in':(t.type==='expense'||t.type==='charge')?'money-out':'';return `<div class="row"><div><strong>${esc(t.note||t.category||'Movimiento')}</strong><div class="meta">${esc(t.date)} · ${finTxLabel(t)}${t.category?' · '+esc(t.category):''}</div></div><div class="right"><strong class="${cls}">${sign}${money(t.amount)}</strong><div class="row-actions"><button class="danger-btn" onclick="deleteFinTx('${t.id}')">Eliminar</button></div></div></div>`}).join(''):'<p class="muted">No hay movimientos financieros.</p>';}
$('#finMovementFilter').onchange=finRenderMovements;
function finTxUi(){const t=$('#finTxType').value;$('#finTxFromWrap').classList.toggle('hidden',t==='income'||t==='charge');$('#finTxToWrap').classList.toggle('hidden',t==='expense');$('#finTxCategoryWrap').classList.toggle('hidden',t==='transfer'||t==='payment');if(t==='income'){$('#finTxTo').innerHTML='<option value="">Cuenta que recibe</option>'+finEscAccountOptions(false)}else if(t==='expense'){$('#finTxFrom').innerHTML='<option value="">Cuenta que paga</option>'+finEscAccountOptions(false)}else if(t==='charge'){$('#finTxTo').innerHTML='<option value="">Tarjeta / deuda</option>'+db.finance.accounts.filter(finIsLiability).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}else if(t==='payment'){$('#finTxFrom').innerHTML='<option value="">Cuenta que paga</option>'+finEscAccountOptions(false);$('#finTxTo').innerHTML='<option value="">Tarjeta / deuda</option>'+db.finance.accounts.filter(finIsLiability).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}else{finRenderSelectors();}}
function finOpenTx(){if(!db.finance.accounts.length)return alert('Primero crea al menos una cuenta.');$('#finTxDate').value=today();$('#finTxAmount').value='';$('#finTxNote').value='';$('#finTxCategory').value='';$('#finTxType').value='expense';finTxUi();$('#finMovementModal').classList.remove('hidden');}
$('#newFinMovement').onclick=finOpenTx;$('#closeFinMovement').onclick=$('#cancelFinTx').onclick=()=>$('#finMovementModal').classList.add('hidden');$('#finTxType').onchange=finTxUi;
$('#saveFinTx').onclick=()=>{const type=$('#finTxType').value,amount=Number($('#finTxAmount').value||0),fromId=$('#finTxFrom').value,toId=$('#finTxTo').value;if(amount<=0)return alert('Ingresa un valor válido.');if((type==='expense'||type==='transfer'||type==='payment')&&!fromId)return alert('Selecciona la cuenta de origen.');if((type==='income'||type==='transfer'||type==='charge'||type==='payment')&&!toId)return alert('Selecciona la cuenta destino.');if(type==='transfer'&&fromId===toId)return alert('Origen y destino deben ser diferentes.');db.finance.transactions.push({id:id(),date:$('#finTxDate').value||today(),type,fromId,toId,category:$('#finTxCategory').value.trim()||((type==='charge'||type==='payment')?'Deudas':'Otros'),amount,note:$('#finTxNote').value.trim()});$('#finMovementModal').classList.add('hidden');save();};
window.deleteFinTx=x=>{if(confirm('¿Eliminar este movimiento financiero?')){db.finance.transactions=db.finance.transactions.filter(t=>t.id!==x);save();}};

function renderAll(){renderClients();renderProducts();renderReceivables();renderHistory();renderCash();renderStats();renderSettings();renderFinance();}

$('#backupBtn').onclick=()=>{const choice=confirm('Aceptar = exportar backup.\nCancelar = importar backup.');if(choice){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='flor-morado-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}else $('#importFile').click();};
$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.clients)||!Array.isArray(x.products)||!Array.isArray(x.sales))throw 0;Object.assign(db,x);db.settings={...DEFAULTS.settings,...(x.settings||{})};db.cashMovements=Array.isArray(x.cashMovements)?x.cashMovements:[];db.finance=x.finance&&typeof x.finance==='object'?x.finance:{accounts:[],transactions:[],recurring:[]};db.finance.accounts=Array.isArray(db.finance.accounts)?db.finance.accounts:[];db.finance.transactions=Array.isArray(db.finance.transactions)?db.finance.transactions:[];db.finance.recurring=Array.isArray(db.finance.recurring)?db.finance.recurring:[];for(const p of db.products)if(p.minStock===undefined)p.minStock=1;for(const s of db.sales){if(!s.orderStatus)s.orderStatus='Pendiente';if(s.shippingExpense===undefined)s.shippingExpense=0;if(s.otherExpenses===undefined)s.otherExpenses=0;if(!Array.isArray(s.payments))s.payments=[];}save();alert('Backup importado correctamente.');}catch{alert('Archivo de backup no válido.');}};r.readAsText(f);};

$('#saleDate').value=today();$('#cashDate').value=today();renderAll();addSaleItem();calcSale();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
