const KEY='florMoradoDB_v1';
const DEFAULTS={clients:[],products:[],sales:[],seq:1,settings:{name:'Flor Morado Muebles',phone:'',address:'',email:'',social:'',city:'',footer:'Gracias por su compra.'}};
let stored={};try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
const db={...DEFAULTS,...stored,settings:{...DEFAULTS.settings,...(stored.settings||{})}};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n||0));
const save=()=>{localStorage.setItem(KEY,JSON.stringify(db));renderAll();};
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
let currentReceiptSaleId=null;

function show(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo({top:0,behavior:'smooth'});} 
$$('.tabs button').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));

function renderClients(){
 $('#saleClient').innerHTML='<option value="">Seleccionar cliente</option>'+db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
 $('#clientList').innerHTML=db.clients.length?db.clients.map(c=>`<div class="row"><div><strong>${esc(c.name)}</strong><div class="meta">${esc(c.phone||'Sin teléfono')} · ${esc(c.address||'Sin dirección')}</div></div><button class="secondary" onclick="deleteClient('${c.id}')">Eliminar</button></div>`).join(''):'<p class="muted">Todavía no hay clientes.</p>';
}
window.deleteClient=x=>{if(confirm('¿Eliminar este cliente?')){db.clients=db.clients.filter(c=>c.id!==x);save();}};
$('#addClient').onclick=()=>{const name=$('#clientName').value.trim();if(!name)return alert('Escribe el nombre del cliente.');db.clients.push({id:id(),name,phone:$('#clientPhone').value.trim(),address:$('#clientAddress').value.trim(),notes:$('#clientNotes').value.trim()});['clientName','clientPhone','clientAddress','clientNotes'].forEach(x=>$('#'+x).value='');save();};

function productExtra(p){return [p.measures,p.color,p.material].filter(Boolean).join(' · ')}
function renderProducts(){
 $('#productList').innerHTML=db.products.length?db.products.map(p=>`<div class="row"><div><strong>${esc(p.name)}</strong><div class="meta">${esc(p.ref||'Sin ref.')} · ${esc(p.category||'Sin categoría')} · Stock: ${Number(p.stock||0)}${productExtra(p)?'<br>'+esc(productExtra(p)):''}${p.details?'<br>'+esc(p.details):''}</div></div><div class="right"><strong>${money(p.price)}</strong><div class="meta">Costo ${money(p.cost)}</div><div class="row-actions"><button class="secondary" onclick="editProduct('${p.id}')">Editar</button><button class="secondary" onclick="adjustStock('${p.id}')">Stock</button></div></div></div>`).join(''):'<p class="muted">Todavía no hay productos.</p>';
 refreshSaleItemSelects();
}
window.adjustStock=x=>{const p=db.products.find(z=>z.id===x);const n=prompt(`Nuevo stock para ${p.name}:`,p.stock);if(n!==null&&!isNaN(n)){p.stock=Number(n);save();}};
window.editProduct=x=>{const p=db.products.find(z=>z.id===x);if(!p)return;$('#prodEditId').value=p.id;$('#prodName').value=p.name||'';$('#prodRef').value=p.ref||'';$('#prodCategory').value=p.category||'';$('#prodMeasures').value=p.measures||'';$('#prodColor').value=p.color||'';$('#prodMaterial').value=p.material||'';$('#prodCost').value=p.cost||0;$('#prodPrice').value=p.price||0;$('#prodStock').value=p.stock||0;$('#prodDetails').value=p.details||'';$('#productFormTitle').textContent='Editar producto';$('#addProduct').textContent='Guardar cambios';$('#cancelProductEdit').classList.remove('hidden');show('inventory');window.scrollTo({top:0,behavior:'smooth'});};
function clearProductForm(){['prodEditId','prodName','prodRef','prodCategory','prodMeasures','prodColor','prodMaterial','prodCost','prodPrice','prodStock','prodDetails'].forEach(x=>$('#'+x).value='');$('#productFormTitle').textContent='Agregar producto';$('#addProduct').textContent='Guardar producto';$('#cancelProductEdit').classList.add('hidden');}
$('#cancelProductEdit').onclick=clearProductForm;
$('#addProduct').onclick=()=>{const name=$('#prodName').value.trim();if(!name)return alert('Escribe el nombre del producto.');const data={name,ref:$('#prodRef').value.trim(),category:$('#prodCategory').value.trim(),measures:$('#prodMeasures').value.trim(),color:$('#prodColor').value.trim(),material:$('#prodMaterial').value.trim(),cost:Number($('#prodCost').value||0),price:Number($('#prodPrice').value||0),stock:Number($('#prodStock').value||0),details:$('#prodDetails').value.trim()};const editId=$('#prodEditId').value;if(editId){const p=db.products.find(x=>x.id===editId);if(p)Object.assign(p,data);}else db.products.push({id:id(),...data});clearProductForm();save();};

function addSaleItem(){const d=document.createElement('div');d.className='sale-item';d.innerHTML=`<label>Producto<select class="item-prod"></select></label><label>Cant.<input class="item-qty" type="number" min="1" value="1"></label><label>Precio<input class="item-price" type="number" min="0" step="1000"></label><button class="remove">×</button>`;$('#saleItems').appendChild(d);d.querySelector('.remove').onclick=()=>{d.remove();calcSale();};d.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',calcSale));d.querySelector('.item-prod').addEventListener('change',e=>{const p=db.products.find(x=>x.id===e.target.value);if(p)d.querySelector('.item-price').value=p.price;calcSale();});refreshSaleItemSelects();}
$('#addSaleItem').onclick=addSaleItem;
function refreshSaleItemSelects(){ $$('.item-prod').forEach(s=>{const cur=s.value;s.innerHTML='<option value="">Seleccionar</option>'+db.products.map(p=>`<option value="${p.id}">${esc(p.name)} (stock ${Number(p.stock||0)})</option>`).join('');s.value=cur;});}
function getSaleDraft(){const items=$$('.sale-item').map(r=>{const productId=r.querySelector('.item-prod').value;const p=db.products.find(x=>x.id===productId);return{productId,qty:Number(r.querySelector('.item-qty').value||0),price:Number(r.querySelector('.item-price').value||0),name:p?.name||'',ref:p?.ref||'',measures:p?.measures||'',color:p?.color||'',material:p?.material||'',details:p?.details||'',cost:Number(p?.cost||0)}}).filter(x=>x.productId&&x.qty>0);const subtotal=items.reduce((a,x)=>a+x.qty*x.price,0);const shipping=Number($('#saleShipping').value||0),discount=Number($('#saleDiscount').value||0),deposit=Number($('#saleDeposit').value||0);const total=Math.max(0,subtotal+shipping-discount),balance=Math.max(0,total-deposit);return{items,subtotal,shipping,discount,deposit,total,balance};}
function calcSale(){const s=getSaleDraft();$('#saleSubtotal').textContent=money(s.subtotal);$('#saleTotal').textContent=money(s.total);$('#saleBalance').textContent=money(s.balance);}['saleShipping','saleDiscount','saleDeposit'].forEach(x=>$('#'+x).addEventListener('input',calcSale));

$('#saveSale').onclick=()=>{const client=db.clients.find(c=>c.id===$('#saleClient').value);if(!client)return alert('Selecciona un cliente.');const d=getSaleDraft();if(!d.items.length)return alert('Agrega al menos un producto.');for(const it of d.items){const p=db.products.find(x=>x.id===it.productId);if(p&&Number(p.stock)<it.qty&&!confirm(`${p.name} tiene stock ${p.stock} y estás vendiendo ${it.qty}. ¿Continuar?`))return;}const number='FM-'+String(db.seq).padStart(4,'0');const sale={id:id(),number,date:$('#saleDate').value||today(),clientId:client.id,payment:$('#salePayment').value,notes:$('#saleNotes').value.trim(),...d,payments:d.deposit?[{id:id(),date:today(),amount:d.deposit,method:$('#salePayment').value,note:'Abono inicial'}]:[]};db.seq++;db.sales.push(sale);for(const it of d.items){const p=db.products.find(x=>x.id===it.productId);if(p)p.stock-=it.qty;}save();renderReceipt(sale);resetSale();};
function resetSale(){$('#saleClient').value='';$('#saleShipping').value=0;$('#saleDiscount').value=0;$('#saleDeposit').value=0;$('#saleNotes').value='';$('#saleItems').innerHTML='';addSaleItem();calcSale();}

function registerPayment(saleId){const s=db.sales.find(z=>z.id===saleId);if(!s||s.balance<=0)return;const raw=prompt(`Saldo actual ${money(s.balance)}.\nValor del abono:`);if(raw===null)return;const a=Number(String(raw).replace(/[^0-9.-]/g,''));if(!a||a<=0)return alert('Ingresa un valor válido.');if(a>s.balance&&!confirm(`El abono supera el saldo por ${money(a-s.balance)}. ¿Registrarlo de todas formas?`))return;const date=prompt('Fecha del abono (AAAA-MM-DD):',today())||today();const method=prompt('Método de pago:',s.payment||'Efectivo')||'';const note=prompt('Nota del abono (opcional):','')||'';s.payments=s.payments||[];s.payments.push({id:id(),date,amount:a,method,note});s.deposit=(s.payments||[]).reduce((sum,p)=>sum+Number(p.amount||0),0);s.balance=Math.max(0,s.total-s.deposit);save();if(!$('#modal').classList.contains('hidden'))renderReceipt(s);}
window.addPayment=registerPayment;
function renderReceivables(){const due=db.sales.filter(s=>s.balance>0);$('#receivableList').innerHTML=due.length?due.map(s=>{const c=db.clients.find(x=>x.id===s.clientId);return `<div class="row"><div><strong>${esc(c?.name||'Cliente')}</strong><div class="meta">${s.number} · ${s.date} · Total ${money(s.total)}</div></div><div class="right"><strong>${money(s.balance)}</strong><div class="row-actions"><button onclick="addPayment('${s.id}')">Registrar abono</button><button class="secondary" onclick="openSale('${s.id}')">Ver</button></div></div></div>`}).join(''):'<p class="muted">No hay saldos pendientes.</p>';}

function renderHistory(){const q=$('#historySearch').value.toLowerCase();const arr=[...db.sales].reverse().filter(s=>{const c=db.clients.find(x=>x.id===s.clientId);return !q||s.number.toLowerCase().includes(q)||(c?.name||'').toLowerCase().includes(q)});$('#historyList').innerHTML=arr.length?arr.map(s=>{const c=db.clients.find(x=>x.id===s.clientId);return `<div class="row"><div><strong>${s.number} · ${esc(c?.name||'Cliente')}</strong><div class="meta">${s.date} · ${money(s.total)}</div></div><div class="right"><span class="badge ${s.balance>0?'debt':'paid'}">${s.balance>0?'Debe '+money(s.balance):'Pagado'}</span><div class="row-actions">${s.balance>0?`<button onclick="addPayment('${s.id}')">+ Abono</button>`:''}<button class="secondary" onclick="openSale('${s.id}')">Ver</button></div></div></div>`}).join(''):'<p class="muted">No hay ventas.</p>';}
$('#historySearch').addEventListener('input',renderHistory);window.openSale=x=>renderReceipt(db.sales.find(s=>s.id===x));

function receiptContact(){const b=db.settings;return [b.address,[b.city,b.phone].filter(Boolean).join(' · '),b.email,b.social].filter(Boolean).map(esc).join('<br>')}
function itemDescription(it){const p=db.products.find(x=>x.id===it.productId)||{};const d={name:it.name||p.name||'Producto',ref:it.ref||p.ref||'',measures:it.measures||p.measures||'',color:it.color||p.color||'',material:it.material||p.material||'',details:it.details||p.details||''};const extra=[d.ref?`Ref. ${d.ref}`:'',d.measures,d.color,d.material,d.details].filter(Boolean).map(esc).join(' · ');return `<strong>${esc(d.name)}</strong>${extra?`<span class="item-detail">${extra}</span>`:''}`;}
function renderReceipt(s){if(!s)return;currentReceiptSaleId=s.id;const c=db.clients.find(x=>x.id===s.clientId);const rows=s.items.map(it=>`<tr><td>${itemDescription(it)}</td><td>${it.qty}</td><td>${money(it.price)}</td><td>${money(it.qty*it.price)}</td></tr>`).join('');const pays=(s.payments||[]);const payRows=pays.length?pays.map((p,i)=>`<div class="payment-row"><span>${i+1}. ${esc(p.date||'')} ${p.method?`· ${esc(p.method)}`:''}${p.note?` · ${esc(p.note)}`:''}</span><strong>${money(p.amount)}</strong></div>`).join(''):'<span class="muted">Sin abonos registrados.</span>';const b=db.settings;$('#receipt').innerHTML=`<div class="receipt"><div class="receipt-head"><img src="logo-flor-morado.jpg" class="receipt-logo" alt="Logo"><div class="receipt-brand"><div class="receipt-kicker">COMPROBANTE DE VENTA / CUENTA DE COBRO</div><h2>${esc(b.name||'Flor Morado Muebles')}</h2><div class="contact">${receiptContact()}</div></div><div class="receipt-number"><span>Comprobante</span><strong>${esc(s.number)}</strong><span>${esc(s.date)}</span></div></div><div class="client-box"><strong>Cliente:</strong> ${esc(c?.name||'')}<br>${c?.phone?`<strong>Teléfono:</strong> ${esc(c.phone)}<br>`:''}${c?.address?`<strong>Dirección:</strong> ${esc(c.address)}`:''}</div><table class="receipt-table"><thead><tr><th>Producto / descripción</th><th>Cant.</th><th>Precio</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table><div class="receipt-total"><div><span>Subtotal</span><strong>${money(s.subtotal)}</strong></div><div><span>Transporte</span><strong>${money(s.shipping)}</strong></div><div><span>Descuento</span><strong>-${money(s.discount)}</strong></div><div class="grand"><span>Total</span><strong>${money(s.total)}</strong></div><div><span>Abonado</span><strong>${money(s.deposit)}</strong></div><div class="grand"><span>Saldo</span><strong>${money(s.balance)}</strong></div></div><div class="payments-box"><h4>Abonos registrados</h4>${payRows}</div><p><strong>Forma de pago inicial:</strong> ${esc(s.payment||'')}</p>${s.notes?`<p><strong>Observaciones:</strong> ${esc(s.notes)}</p>`:''}<div class="receipt-footer">${b.footer?`<div>${esc(b.footer)}</div>`:''}<div>Documento interno de venta. No constituye factura electrónica.</div></div></div>`;$('#paymentFromReceipt').classList.toggle('hidden',!(s.balance>0));$('#modal').classList.remove('hidden');}
$('#paymentFromReceipt').onclick=()=>currentReceiptSaleId&&registerPayment(currentReceiptSaleId);
$('#closeModal').onclick=$('#closeModal2').onclick=()=>{$('#modal').classList.add('hidden');currentReceiptSaleId=null;};$('#printReceipt').onclick=()=>window.print();

function renderStats(){const now=new Date(),ym=now.toISOString().slice(0,7);const ms=db.sales.filter(s=>String(s.date||'').startsWith(ym));$('#statSales').textContent=money(ms.reduce((a,s)=>a+s.total,0));let prof=0;for(const s of ms)for(const it of s.items){const p=db.products.find(x=>x.id===it.productId);const cost=('cost'in it)?Number(it.cost||0):Number(p?.cost||0);prof+=(it.price-cost)*it.qty;}$('#statProfit').textContent=money(prof);$('#statDebt').textContent=money(db.sales.reduce((a,s)=>a+s.balance,0));$('#statLow').textContent=db.products.filter(p=>Number(p.stock)<=1).length;}

function renderSettings(){const b=db.settings;$('#bizName').value=b.name||'';$('#bizPhone').value=b.phone||'';$('#bizAddress').value=b.address||'';$('#bizEmail').value=b.email||'';$('#bizSocial').value=b.social||'';$('#bizCity').value=b.city||'';$('#bizFooter').value=b.footer||'';}
$('#saveSettings').onclick=()=>{db.settings={name:$('#bizName').value.trim()||'Flor Morado Muebles',phone:$('#bizPhone').value.trim(),address:$('#bizAddress').value.trim(),email:$('#bizEmail').value.trim(),social:$('#bizSocial').value.trim(),city:$('#bizCity').value.trim(),footer:$('#bizFooter').value.trim()};save();alert('Datos del negocio guardados.');};

function renderAll(){renderClients();renderProducts();renderReceivables();renderHistory();renderStats();renderSettings();}

$('#backupBtn').onclick=()=>{const choice=confirm('Aceptar = exportar backup.\nCancelar = importar backup.');if(choice){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='flor-morado-backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href);}else $('#importFile').click();};
$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.clients||!x.products||!x.sales)throw 0;Object.assign(db,x);db.settings={...DEFAULTS.settings,...(x.settings||{})};save();alert('Backup importado correctamente.');}catch{alert('Archivo de backup no válido.');}};r.readAsText(f);};

$('#saleDate').value=today();renderAll();addSaleItem();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
